// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_eT2d8aswNqHvWAb6NCyVbvSO8Sd0eg',
    appId: '1:499179503240:web:02f0fda889b0d17b10293d',
    messagingSenderId: '499179503240',
    projectId: 'propertypulse-cec60',
    authDomain: 'propertypulse-cec60.firebaseapp.com',
    storageBucket: 'propertypulse-cec60.firebasestorage.app',
    measurementId: 'G-7V5MJR6ZVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqy3ZjtiPma7kWVHIScn4sqRWg40UbMfY',
    appId: '1:499179503240:android:0dc0aabcf55c161810293d',
    messagingSenderId: '499179503240',
    projectId: 'propertypulse-cec60',
    storageBucket: 'propertypulse-cec60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtF6odeHDwEPmReZBIGFpQyNJtmv5KjG4',
    appId: '1:499179503240:ios:b3e7391d196c0ec910293d',
    messagingSenderId: '499179503240',
    projectId: 'propertypulse-cec60',
    storageBucket: 'propertypulse-cec60.firebasestorage.app',
    iosBundleId: 'com.example.madProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtF6odeHDwEPmReZBIGFpQyNJtmv5KjG4',
    appId: '1:499179503240:ios:b3e7391d196c0ec910293d',
    messagingSenderId: '499179503240',
    projectId: 'propertypulse-cec60',
    storageBucket: 'propertypulse-cec60.firebasestorage.app',
    iosBundleId: 'com.example.madProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv_eT2d8aswNqHvWAb6NCyVbvSO8Sd0eg',
    appId: '1:499179503240:web:f7931377986af10410293d',
    messagingSenderId: '499179503240',
    projectId: 'propertypulse-cec60',
    authDomain: 'propertypulse-cec60.firebaseapp.com',
    storageBucket: 'propertypulse-cec60.firebasestorage.app',
    measurementId: 'G-E7E2C913HJ',
  );
}
